backend:
  name: github
  repo: jay1roy/syeire # This should be your actual GitHub repo name
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"  # This should match your actual file location for content (or change to a working folder)
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
