backend:
  name: github  # Directly use GitHub (no Netlify dependency)
  repo: jay1roy/syeire  # Your GitHub repo
  branch: main  # Your default branch
  auth_type: implicit  # Required for GitHub OAuth
  site_domain: syeire1.pages.dev  # Your Cloudflare Pages domain

media_folder: "static/uploads"  # Where images will be stored
public_folder: "/uploads"  # Public path for images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
